version: '3.7'
services:
    tinkerpop:
        image: tinkerpop/gremlin-server:3.4.9
        environment: []
        volumes:
        - ./tinkergraph-empty.properties:/opt/gremlin-server/conf/tinkergraph-empty.properties
        - ./gremlin-server.yaml:/opt/gremlin-server/conf/gremlin-server.yaml
        - ./gremlin.sh:/docker-entrypoint.sh
        ports:
            - "8182:8182"
        command: "/opt/gremlin-server/conf/gremlin-server.yaml"
    jupyter:
        build: .
        restart: always
        depends_on:
            - tinkerpop
        environment: []
        volumes: []
        ports:
            - "8888:8888"
